- inst/include/cpp11/environment.hpp
- inst/include/cpp11/external_pointer.hpp
- inst/include/cpp11/list_of.hpp
Some files were missing header guards making it impossible to include them in multiple files
> Add header guards to header files that lacks them

- .github/workflows/R-CMD-check.yaml
Given that you are doing compiler specific things, and you want to support old versions of R, I think it is important to also test a configuration with the old Windows toolchain.
I think testing for `r: 3.6` suffices because Windows uses the same toolchain as R 3.3 - 3.6.
> GHA: test with old Windows toolchain

- R/register.R
- man/cpp_register.Rd
- tests/testthat/test-register.R
This PR adds an argument `quiet` that prevents the informational output from cli during registration. Ideally this would also be passed down by pkgbuild, though this looks like a long call path (build -> build_setup -> update_registration -> compile_rcpp_attributes -> cpp11::cpp_register).
The context here is that we're looking at using cpp11 rather than Rcpp in a code generation system, so am looking to avoid this noise when a user has passed a verbose/quiet flag in at our end - we can use `suppressMessages` but that's a big hammer.
> Optionally register quietly

- inst/include/cpp11/matrix.hpp
This PR eliminates a compiler warning seen with `-pedantic` with 8.4.0:
```
In file included from /home/u00u4okcre0eieqDxq357/R/x86_64-pc-linux-gnu-library/4.0/dust/include/dust/interface.hpp:6,
from sirs.cpp:4:
/home/u00u4okcre0eieqDxq357/R/x86_64-pc-linux-gnu-library/4.0/cpp11/include/cpp11/matrix.hpp:108:2: warning: extra ';' [-Wpedantic]
};  // namespace cpp11
```
> Drop unneeded trailing semicolon

- inst/include/cpp11/as.hpp
I believe this is required when `T` declares the constructor taking a `SEXP` as explicit.
> explicit conversion

- cpp11test/src/test-logicals.cpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
closes #56
``` r
cpp11::cpp_function('
cpp11::writable::logicals bools(){ 
cpp11::writable::logicals x(1);
x[0] = true;
return x;
} 
', quiet = FALSE)
#> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/romainfrancois/.R/library/4.0/cpp11/include  -I/usr/local/include   -fPIC  -Wall -O3 -Wall -Wimplicit-int-float-conversion -c /private/var/folders/4b/hn4fq98s6810s4ccv2f9hm2h0000gn/T/RtmpHcARkQ/file494f394b9440/src/code_0.cpp -o /private/var/folders/4b/hn4fq98s6810s4ccv2f9hm2h0000gn/T/RtmpHcARkQ/file494f394b9440/src/code_0.o
#> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/romainfrancois/.R/library/4.0/cpp11/include  -I/usr/local/include   -fPIC …
```
> allow = <bool> in writables::logicals.

- NEWS.md
- cpp11test/src/test-as.cpp
- inst/include/cpp11/as.hpp
This is mostly useful for `NA` : 
``` r
cpp11::cpp_function("int echo(int x){ return x; }")
str(echo(1))
#>  int 1
str(echo(2L))
#>  int 2
str(echo(NA))
#>  int NA
```
<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
> as_cpp<int>(LGLSXP scalar)

- cpp11test/src/test-list.cpp
- inst/include/cpp11/list.hpp
modeled after `r_vector<r_string>::const_iterator::operator*`. 
This would otherwise fail as `*it` would give a `nullptr`
``` r
cpp11::cpp_function('SEXP premier(cpp11::list x) {
auto it = x.begin(); 
return *it;
}', quiet = FALSE)
#> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/romainfrancois/.R/library/4.0/cpp11/include  -I/usr/local/include   -fPIC  -Wall -O3 -Wall -Wimplicit-int-float-conversion -c /private/var/folders/4b/hn4fq98s6810s4ccv2f9hm2h0000gn/T/Rtmp3hU7Um/file11df6d2e2e10/src/code_0.cpp -o /private/var/folders/4b/hn4fq98s6810s4ccv2f9hm2h0000gn/T/Rtmp3hU7Um/file11df6d2e2e10/src/code_0.o
#> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG …
```
> + list::const_iterator::operator*

- cpp11test/src/safe.cpp
- cpp11test/src/test-protect.cpp
- inst/include/cpp11/protect.hpp
The explicit suffix is not necessary since `unwind_protect` is overloaded to handle both return types
https://github.com/r-lib/cpp11/pull/54#discussion_r461597780
> remove unwind_protect_sexp

- inst/include/cpp11/protect.hpp
Not sure this the right syntax, but without the `throw;` I was getting compiler warnings. https://en.cppreference.com/w/cpp/language/attributes/noreturn
This is particularly useful when using switch'es, as in this example from `arrow`: 
```cpp
SEXP from_datum(arrow::Datum datum) {
switch (datum.kind()) {
case arrow::Datum::SCALAR:
return cpp11::as_sexp(datum.scalar());
case arrow::Datum::ARRAY:
return cpp11::as_sexp(datum.make_array());
case arrow::Datum::CHUNKED_ARRAY:
return cpp11::as_sexp(datum.chunked_array());
case arrow::Datum::RECORD_BATCH:
return cpp11::as_sexp(datum.record_batch());
case arrow::Datum::TABLE:
return cpp11::as_sexp(datum.table());
default:
break;
}
auto str = datum.ToString();
cpp11::stop("from_datum: Not implemented for Datum %s", str.c_str());
}
```
> mark stop() with [[noreturn]] attribute

- .gitignore
- NEWS.md
- cpp11test/src/test-as.cpp
- inst/include/cpp11/as.hpp
> as_cpp<Enum>

- NEWS.md
- inst/include/cpp11/protect.hpp
fixes #69
repro: https://wandbox.org/permlink/po7niLIoJ9HgJ74p
fixed: https://wandbox.org/permlink/RTg6mAArF13XyuRU
There are more sophisticated/general implementations of make_index_sequence/apply if desired
> capture parameter pack as a tuple to work around gcc4.8

- cpp11test/src/test-as.cpp
- inst/include/cpp11/as.hpp
- inst/include/cpp11/r_string.hpp
Also cleaned up some reliance in the traits on implicit conversions, which can be painful to debug
> refactor traits to conventional enable_if_ prefix

- cpp11test/src/test-as.cpp
- inst/include/cpp11/as.hpp
Follow up to #65 
Some enum classes in arrow have `char` as their underlying type and this avoids `as_cpp<char>()` which apparently doesn't compile. 
closes #73
> handle enum with underlying type char

- .gitignore
- cpp11test/src/test-protect.cpp
- inst/include/cpp11/protect.hpp
I also cleaned up the signatures of detail:: functions, hopefully it's more readable
> workaround mangle collision between decltype(Rf_error) and decltype(Rf_warning)

- inst/include/cpp11/as.hpp
Some compilers seem to be confused about `std::shared<T>` being constructible from SEXP. 
https://github.com/apache/arrow/pull/7819/checks?check_run_id=993750889#step:8:3524
```
array_from_vector.cpp: In function ‘std::shared_ptr<arrow::DataType> arrow::r::InferArrowTypeFromVector(SEXP) [with int VectorType = 4; SEXP = SEXPREC*]’:
3525
array_from_vector.cpp:1198:58: error: call of overloaded ‘as_cpp(SEXPREC*&)’ is ambiguous
3526
return cpp11::as_cpp<std::shared_ptr<arrow::Array>>(x)->type();
3527
^
3528
array_from_vector.cpp:1198:58: note: candidates are:
3529
In file included from /opt/R/3.6.3/lib/R/library/cpp11/include/cpp11.hpp:5:0,
3530
from ././arrow_cpp11.h:34,
3531
from ./arrow_types.h:22,
3532
from array_from_vector.cpp:20:
3533 …
```
> special case as_cpp<SEXP>()

- inst/include/cpp11/as.hpp
> disable smart pointers (shared, unique, weak) from as_cpp<'constructible from SEXP'>

- .gitignore
- R/utils.R
- cpp11test/src/protect.cpp
- cpp11test/src/test-sexp.cpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/protect.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/sexp.hpp
- inst/include/cpp11/strings.hpp
- tests/testthat/test-source.R
- vignettes/internals.Rmd
- Renamed from `protect_sexp/release_protect/...` to `preserved.insert/preserved.release` to highlight the similarity in intent to `R_PreserveObject` and decrease the semantic overload of "protect"
- Moved the doubly-linked list of preserved objects from a static object in c++ named `cpp11::protect_list` to an internal in R named `cpp11:::.preserve_list`. This allows the list to be a singleton since any shared object we load will look up the same `cpp11:::.preserve_list`. By contrast a new c++ static variable will be instantiated for each translation unit we compile, resulting in multiple unrelated preserve_lists:
```r
cpp11::cpp_function('SEXP protect_one(SEXP e) { cpp11::protect_sexp(e); return e; }')
cpp11::cpp_function('int protected_count() { return Rf_length(cpp11::protect_list) - …
```
> Preserved list refactor

- NEWS.md
- cpp11test/src/test-as.cpp
- cpp11test/src/test-list.cpp
- cpp11test/src/test-logicals.cpp
- inst/include/cpp11.hpp
- inst/include/cpp11/R.hpp
- inst/include/cpp11/external_pointer.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/matrix.hpp
- inst/include/cpp11/protect.hpp
- inst/include/cpp11/r_bool.hpp
- vignettes/converting.Rmd
- vignettes/cpp11.Rmd
> Add r_bool wrapper for Rboolean

- NEWS.md
- inst/include/cpp11/protect.hpp
Using an environment as previously done generates a stack overflow when
serialized.
The data part of XPtrs is not serialized, so avoids this issue, while
also avoiding the copying issues that prompted use of an environment.
> Store the protect list as an XPtr rather than in an environment

- NEWS.md
- inst/include/cpp11/protect.hpp
XPtrs are marked as null when restoring, so we need to check for this
and we also now check that the option is a pairlist before trying to
read its value
Fixes #121
> Make preserve list more robust to bad values

- R/register.R
Without this flag, an object 'res' is created in the user's global environment
Reprex to see the issue:
```r
local({
path <- tempfile()
dir.create(path)
dir.create(file.path(path, "src"))
dir.create(file.path(path, "R"))
writeLines(c("Package: pkg", "Version: 0.1.0", "LinkingTo: cpp11"),
file.path(path, "DESCRIPTION"))
writeLines("useDynLib(pkg, .registration = TRUE)",
file.path(path, "NAMESPACE"))
writeLines(c("[[cpp11::register]]",
"double add(double a, double b) {",
"  return a + b;",
"}"),
file.path(path, "src", "code.cpp"))
cpp11::cpp_register(path)
})
ls(.GlobalEnv)
#> [1] "res"
head(res)
#> [1] "#include <R.h>"                  "#include <Rinternals.h>"        
#> [3] "#include <stdlib.h> // for NULL" "#include <R_ext/Rdynload.h>"    
#> [5] ""                                "/* …
```
> Use a local textConnection object

- vignettes/cpp11.Rmd
Without this, explicitly following the current instructions of just adding `LinkingTo` fails, likely leaving many to attempt `usethis::use_cpp11()`, which also fails because of [this :bug:](https://github.com/r-lib/usethis/pull/1329). Once `use_cpp11()` works after *only* adding `LinkingTo`, and not `useDynLib`, and once the vignette has been updated with this PR, then the entire procedure should be sufficiently robust that any potential combination of these approaches should give the desired result of enabling use of `cpp11`. Thanks as always @jimhester  for the awesome work. Hope that helps!
> describe addition of useDynLib in cpp11 vignette

- vignettes/converting.Rmd
The code example that intends to save the R RNG state was broken: `local_rng();` creates a temporary object that ceases existing at the end of the full expression, i.e. *before* the rest of the body of the function `foo` is executed. To prevent this, the object *must* be named.
Additionally, depending on the compiler settings, the above might cause an “unused object” warning (though GCC 10 doesn’t even with `-Wunused-variable`, because this usage pattern is recognised).
A common solution is to wrap the scope guard usage into a macro:
```cpp
#define PASTE1(x, y) x ## y
#define PASTE(x, y) PASTE1(x, y)
#define RNG_GUARD auto PASTE(_rng, __LINE__) = local_rng(); (void) PASTE(_rng, __LINE__)
…
void foo() {
RNG_GUARD;
}
```
… or one could use a wrapper similar to `unwind_protect`.
> Fix RNG code example in `converting.Rmd`

- DESCRIPTION
- NEWS.md
- R/source.R
- tests/testthat/test-source.R
This PR adds escaping of spaces in path names that are written to the `Makevars` file used by ‘cpp11’ for compilation.
I came across this issue because I’m keeping my R package library on macOS in the standard config location, which is `~/Library/Application Support` (note the space). Since ‘cpp11’ adds its own installation directory to the include path, this consequently causes an error when invoking e.g. `cpp_source()`, which looks as follows:
>     clang: error: no such file or directory: 'Support/R/4.0/library/cpp11/include'
>     make: *** [/private/var/folders/dr/rp46tjqs5qzfj_ghjpxqrttr0000gn/T/RtmpMtBJTo/file13e521450b665/src/code_13e523ef6ab4e.o] Error 1
>     Error: Compilation failed.
> Fix handling of whitespace in Makevars filename

- NEWS.md
- R/register.R
Used withr::with_collate to temporarily use C collation and updated NEWS.md with fix
fixes #171
> Feature use c collation

- .gitignore
- R/source.R
Modified base names break navigation to  the original file location on errors (in my case emacs/ESS). Modifying only the shared lib path at the end would have the same effect of registering dyn lib with a new name.
> Don't modify the file name on cpp_source, only the shared lib name

- R/source.R
- tests/testthat/test-source.R
This should fix the R CMD check errors and still prevent source file name changes.
> Bug - cpp11 source file names

- NEWS.md
- cpp11test/src/test-list.cpp
- inst/include/cpp11/r_vector.hpp
Added news updates for both `named()` and `empty()` to this PR
fixes #182
> adding empty to vector classes

- NEWS.md
- cpp11test/src/test-list.cpp
- inst/include/cpp11/r_vector.hpp
> added r_vector named() method

- cpp11test/src/test-logicals.cpp
- cpp11test/src/test-strings.cpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/strings.hpp
> Workaround issue constructing logical vectors of length 1 from 'false'

- inst/include/cpp11/protect.hpp
The internal protection can be skipped if we are already in an
unwind_protect call.
Fixes #141
> Support more efficient nesting of unwind_protect

- inst/include/cpp11/r_vector.hpp
Looks like CI won't catch this since it only runs R >= 3.4, but logically this looks right to me.
> Fix compilation on R 3.3

- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
I think it should mention REALSXP for doubles and INTSXP for integers when throwing type_error.
> Fix type_error when constructing integers & doubles

- NEWS.md
- inst/include/cpp11/r_vector.hpp
IIRC, + should return new object, and += should modify the existing one.
> Fix semantics of + and += for r_vector::iterator

- NEWS.md
- cpp11test/R/cpp11.R
- cpp11test/src/cpp11.cpp
- cpp11test/src/matrix.cpp
- cpp11test/src/test-matrix.cpp
- cpp11test/tests/testthat/test-matrix.R
- inst/include/cpp11/matrix.hpp
- vignettes/cpp11.Rmd
This draft PR adds `matrix::column` class in full analogy to `matrix::row` class and updates the matrix API so that both rows and columns could be accessed. I just added it because my use-case required column-wise access.
I'm not sure about the proposed matrix API, it was just the easiest to implement.
Alternatively one could think about `matrix::row_vector` proxy class and `matrix::rows()` method that would provide row access (begin/end/[] etc) and `matrix::column_vector` that would provide symmetric columns access.
I also added the required types to `matrix::row::iterator` so that it actually conforms to the iterator concept.
> Columns support for matrix class

- NEWS.md
- inst/include/cpp11/protect.hpp
It seems relying on non-local static objects can cause memory issues,
that are resolved by moving to use a local static objects instead.
Fixes #244
> Fix crash related to unwind protect short circuiting

- vignettes/cpp11.Rmd
Great vignette!  This PR just fixes a couple of tiny typos where variable names hadn't been swapped over from the original ones from Advanced R.
> Fix small typo in "cpp11" vignette

- NEWS.md
- R/source.R
- tests/testthat/_snaps/source.md
- tests/testthat/test-source.R
If I call `cpp_source()` with a nonexistent filepath, interactively I see:
```
> devtools::load_all(".")
ℹ Loading cpp11
> cpp_source("asdfuiop.cpp")
Error in startsWith(decorations$decoration, "cpp11::") : 
non-character object(s)
```
I'm not sure why the first snapshot in this PR shows a different (but also non informative) error. But, in any case, it seems better to check early for the existence of `file` and to fail in a more specific way, if `file` does not exist.
> Fail fast and informatively for nonexistent file

- .github/workflows/R-CMD-check.yaml
- .github/workflows/format.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- DESCRIPTION
- NEWS.md
- README.md
- cpp11test/src/test-doubles.cpp
- cpp11test/src/test-integers.cpp
- cpp11test/src/test-protect.cpp
This PR was originally intended to update the GitHub Actions workflow files in cpp11, but doing so proved to be quite challenging since they haven't been updated in awhile.
Note that there are more files changed here than just the workflow files, because we needed to tweak some of the actual cpp11 tests to accommodate some other problems. I will point them out with inline comments describing them in detail.
You should also be able to look at the individual commits to track the changes, I have tried to make them meaningful.
> Update GitHub Actions workflows, and make necessary tweaks to support them

- NEWS.md
- tests/testthat/test-register.R
since https://github.com/r-devel/r-svn/commit/acd91c3a24923e42562f5b663a64d389e7e06997
in response to cran email:
```
Dear maintainer,
Please see the problems shown on
<https://www.google.com/url?q=https://cran.r-project.org/web/checks/check_results_cpp11.html&source=gmail-imap&ust=1665988745000000&usg=AOvVaw0TUXx2J7KBy_EgFalrLd2O>.
Please correct before 2022-10-24 to safely retain your package on CRAN.
The CRAN Team
```
> `.Call()` entries might have `(void)`

- DESCRIPTION
- NEWS.md
- R/register.R
- R/source.R
- R/utils.R
- man/cpp_register.Rd
- tests/testthat/_snaps/register.md
- tests/testthat/helper.R
- tests/testthat/test-register.R
- tests/testthat/test-utils.R
So that e.g. the testthat output is less verbose:
> `cpp_register(quiet=)` set to TRUE on non-interactive session (incl testthat runs)

- DESCRIPTION
- _pkgdown.yml
For two reasons:
- To be consistent with other r-lib pkgdown websites
- To make it easy for users to search for information
cc @romainfrancois
> Switch to bootstrap 5 for pkgdown website

- NEWS.md
- inst/include/cpp11/R.hpp
See https://github.com/r-lib/systemfonts/issues/98 for the original issue. That issue turned out to be a different _error_, but this PR still silences the _warning_ that appeared there. The original issue poster confirmed that this PR fixed the warning.
---
On the Intel compiler (icpc), it looks like our pragmas to disable unknown attribute warnings are not working, i.e. in the original issue the user saw:
```cpp
In file included from caches.cpp(1):
caches.h(22): warning #3924: attribute namespace "cpp11" is unrecognized
[[cpp11::init]]
```
On the Intel compiler, it looks like you disable warnings using the diagnostic number instead, in this case that is the `#3924` you see in the warning output above. The following two resources support this. In particular, the second resource disables …
> Use Intel specific pragma to disable unknown attribute warning

- DESCRIPTION
- R/register.R
- tests/testthat/test-register.R
In the next version of glue, `glue::glue_collapse()` will never return `character()` but instead will return `""` for empty inputs. For more detail see https://github.com/tidyverse/glue/pull/295.
This makes the necessary change inside cpp11 and places 2 temporary skips in the tests so cpp11 can be released before glue. Interestingly, this actually makes the tests match their existing descriptions.
I won't release glue for at least two weeks (so: March 31) and it will likely be later.
> Respond to upcoming changes in `glue::glue_collapse()`

- vignettes/cpp11.Rmd
I found a very minor thing in the cp11 vignette in the Missing values section. Markdown renders need lists to have a preceding blank line in order to render properly.
Before this change, the corresponding text rendered like:
> If you’re working with missing values, you need to know two things: * How R’s missing values behave in C++’s scalars (e.g., double). * How to get and set missing values in vectors (e.g., doubles).
After:
> If you’re working with missing values, you need to know two things:
>
> * How R’s missing values behave in C++’s scalars (e.g., double).
> * How to get and set missing values in vectors (e.g., doubles).
I made a guess the current rendering wasn't intentional but feel free to close if it was.
> Fix minor formatting issue in cpp11 vignette

- inst/include/cpp11/list_of.hpp
Read only version of list_of operator[] functions was missing const modifiers.  As a result, when trying to access list elements, 1. const list_of ends up calling list's operator[] functions thus without auto type conversion, and 2 if forcing to use list_of::operator[],  we encounter compiler error that the call "discards const-ness".
> FIX: list_of operator[] missing const modifiers.

- DESCRIPTION
- NEWS.md
- R/register.R
- man/cpp_register.Rd
- tests/testthat/test-register.R
> new extension= argument for cpp_register()

- NEWS.md
- inst/include/cpp11/protect.hpp
Closes #298 
@jimhester would you mind reviewing this for me? You are the last one to have touched this code, and probably understand it better than anyone else. The #298 issue provides the backstory.
A rerun of the benchmark in #298 gives me:
```r
bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 test(x)    715.35ms 751.55ms      1.31    7.63MB     1.96
#> 2 test2(x)     7.65ms   9.11ms    100.      7.63MB    35.1
bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: …
```
> Move `static` local variable out of templated function

- inst/include/cpp11/R.hpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_bool.hpp
- inst/include/cpp11/r_string.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
This PR attempts to force `data_p_` to always be a pointer to the "underlying" type of `SEXP data_`.
Currently, this is not the case. `data_p_` currently has type `T*`, which means that for various vectors it maps to:
- integers: `int*`
- doubles: `double*`
- logicals: `r_bool*` (rather than `int*`)
- raws: `uint8_t*` (rather than `Rbyte*`)
- list: not used, but would be `SEXP*`
- strings: not used, but would be `r_string*` (rather than `SEXP*`)
- complexes: not implemented (yet!, but it is built on top of this here https://github.com/DavisVaughan/cpp11/pull/2)
The `logicals` and `raws` cases make me a little nervous. When `data_p_` is set for these classes, it is done so like:
```cpp
data_p_ = reinterpret_cast<r_bool*>(LOGICAL(data))
```
I think we can avoid this by instead ensuring that …
> Ensure that `data_p_` is typed with the underlying type of `data_`

- .github/workflows/R-CMD-check.yaml
- Makefile
- NEWS.md
- cpp11test/R/cpp11.R
- cpp11test/src/cpp11.cpp
- cpp11test/src/test-doubles.cpp
- cpp11test/src/test-integers.cpp
- inst/include/cpp11/R.hpp
- inst/include/cpp11/as.hpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
This reverts commit 3c877986ce886b320ceafb853358d856f07834f4.
> Fix missing value propagation in `as_integers/doubles()`, take 2

- README.md
- cpp11test/DESCRIPTION
- vignettes/converting.Rmd
- vignettes/cpp11.Rmd
> remove recommendation to specify `SystemRequirements: C++11`

- NEWS.md
- cpp11test/R/cpp11.R
- cpp11test/src/cpp11.cpp
- cpp11test/src/test-protect-nested.cpp
- inst/include/cpp11/protect.hpp
- vignettes/FAQ.Rmd
- vignettes/internals.Rmd
Closes #325 
Closes #326 
Note that this makes the example from https://github.com/r-lib/cpp11/issues/298 very slow again, because nested `unwind_protect()` is no longer "optimized". This is an example where character vector manipulation may be better with a manual `unwind_protect()` + R C API usage
> Remove `cpp11_should_unwind_protect` altogether

- NEWS.md
- inst/include/cpp11/protect.hpp
- vignettes/internals.Rmd
Closes https://github.com/r-lib/cpp11/issues/330 (see this issue for full discussion)
Closes https://github.com/r-lib/cpp11/issues/268 (as there is no longer a global option)
This is the minimal amount of work to move from a global protection list to 1 protection list per compilation unit.
In two follow up PRs I will:
- Remove `release_all()`, require R >= 3.5.0, remove `CPP11_USE_PRESERVE_OBJECT` and its related code (not much), remove the documentation section about R 3.5.0 and the tradeoffs about unwind-protect (#332)
- Talk to Lionel about how best to include the package name in a debug macro somehow, to make it easier to debug protection issues
> Create 1 preserve list per compilation unit

- DESCRIPTION
- NEWS.md
- inst/include/cpp11/protect.hpp
- vignettes/internals.Rmd
Tied to https://github.com/r-lib/cpp11/pull/331, where we switch from a global preserve list to 1 preserve list per compilation unit. `release_all()` was intended to support experts that wanted to manually release cpp11 protected objects on R < 3.5.0, but it no longer is applicable for a few reasons:
- In the tidyverse we now require R >=3.6.0 in most places
- Using 1 preserve list per compilation unit means it will now only release objects managed by that compilation unit's preserve list
- We think the idea of potentially releasing objects you don't own can be dangerous (like if you accidentally release vroom ALTREP objects, which can persist past a `.Call()` boundary)
No one was using `release_all()` as far as we can tell.
---
I've also bumped the minimum R version to >=3.5.0, so we no …
> Require R >=3.5.0 and remove `release_all()`

- NEWS.md
- inst/include/cpp11/protect.hpp
- inst/include/cpp11/sexp.hpp
Not sure exactly why this issue popped up on CI ( https://github.com/apache/arrow/pull/38894#issuecomment-1828488227 ), but it seems that at least one format string has `%x` (which expects an `int`) where I think the intention was to print memory addresses (i.e., `%p`). Our CI issue is probably because we're being a tad to aggressive about converting errors to warnings, but it seemed like an easy fix while I was taking a look!
> Ensure format strings pass check in R-devel/Windows

- .Rbuildignore
- .gitignore
- vignettes/FAQ.Rmd
- vignettes/converting.Rmd
- vignettes/cpp11.Rmd
- vignettes/internals.Rmd
- vignettes/motivations.Rmd
Enforced sentence wrapping, trimmed multiple spaces between words, aligned tables, removed extra newlines, etc.
Did a quick double check against the pkgdown site built locally to make sure it all looks good still
> Modernize all vignettes with quarto visual editor preferences

- .github/workflows/R-CMD-check.yaml
Using https://github.com/r-lib/actions/pull/879
> Try using actions PR for 3.6 support

- NEWS.md
- cpp11test/src/protect.cpp
- cpp11test/src/test-protect.cpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/protect.hpp
- inst/include/cpp11/r_bool.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/sexp.hpp
- inst/include/cpp11/strings.hpp
- vignettes/internals.Rmd
Closes https://github.com/r-lib/cpp11/issues/249 as a cool side effect
The `preserved` static struct object has been removed in favor of some inline functions `detail::store::insert()` and `detail::store::release()`. These both access the preserve list through a _static local SEXP in an extern function_ called `detail::store::get()`. This exact setup is guaranteed by the standard to mean that the preserve list is _unique across compilation units_ in the package (see notes and links to SO and the standard in `protect.hpp`).
While working on https://github.com/r-lib/cpp11/pull/366, I learned that the current approach with the static `preserved` seems to have some issues anyways. The tests I implemented there were not consistently passing on all platforms, and seemed to change on my Mac …
> Simplify preserve list approach

- NEWS.md
- cpp11test/src/test-integers.cpp
- cpp11test/src/test-list.cpp
- inst/include/cpp11/r_vector.hpp
Closes #338 
This is rather complicated, and is caught up in the fact that we currently double protect all writable r_vectors (oops), but this is the minimal fix for #338. More changes are coming to simplify things further.
Here's the basic idea of what was happening (glossing over double protect weirdness). Take this example:
```cpp
cpp11::writable::integers x(1);
x = cpp11::writable::integers(1);
```
Here are the protection counts:
- `+1 x` The constructor creates `x` and protects it
- `+1 <temp>` An rvalue (temporary) of `cpp11::writable::integers(1)` is created and protected
- `+1 <temp>` WRONG! The move assignment operator is re-protecting the rvalue SEXP as it takes ownership of it rather than just taking the protect token from the rhs.
- `-1 x` The move assignment operator releases …
> Fix memory leak with move assignment operator

- NEWS.md
- cpp11test/R/cpp11.R
- cpp11test/bench/truncate.R
- cpp11test/src/cpp11.cpp
- cpp11test/src/sum_rcpp.cpp
- cpp11test/src/truncate.cpp
- inst/include/cpp11/r_vector.hpp
- vignettes/motivations.Rmd
Closes https://github.com/r-lib/cpp11/issues/355
Closes https://github.com/r-lib/cpp11/pull/358
In cpp11 we used 3 non-API calls:
- `SETLENGTH()`
- `SET_TRUELENGTH()`
- `SET_GROWABLE_BIT()`
The combination of these 3 allowed us to implement efficient growable `r_vector`s. See:
https://github.com/r-lib/cpp11/blob/aeb67b3f354152974cd06d5c6af7145e6ddd0717/inst/include/cpp11/r_vector.hpp#L898-L926
We absolutely cannot use these functions anymore. However, growable vectors are still pretty nice. The only viable alternative for cpp11 (as a header only package) seems to be to use `Rf_xlengthgets()` instead, so that is what this PR does.
> Side note: In rlang, we are probably going to work around this by implementing ALTREP views. "Truncation" is just a contiguous view into `x` (with size …
> Avoid non-API calls when truncating overallocated vectors

- inst/include/cpp11/list_of.hpp
- inst/include/cpp11/r_vector.hpp
Should make it much easier to understand the classes just by looking at the class definition now, with all implementations separated out below
Also fixed a few minor inconsistencies, like a declaration requesting `const R_xlen_t pos` but the impl using `R_xlen_t pos`, not a big deal.
No behavior changes
> Clean up read-only `r_vector` declaration / implementation split

- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
Closes https://github.com/r-lib/cpp11/issues/368 - this issue doesn't matter too much, but if you start as a writable ALTREP object and then call `push_back()` and that resizes the vector, then it will still look like an ALTREP object even though `Rf_xlengthgets()` will never produce an ALTREP object. The right thing to do is to always recompute the flag from the newly allocated object.
When working on this, I realized we could unify the `reserve()` methods, removing a lot of duplication, which is great. It now also sets the `data_p_` for VECSXP and STRSXP which was not happening before, but `get_p()` will always return `nullptr` for these types, so no harm done.
> Use a universal `reserve()` method

- cpp11test/src/test-doubles.cpp
- cpp11test/src/test-integers.cpp
- cpp11test/src/test-list.cpp
- cpp11test/src/test-logicals.cpp
- cpp11test/src/test-raws.cpp
- cpp11test/src/test-strings.cpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
Closes https://github.com/r-lib/cpp11/issues/375
Strings are a bit complicated and require their own specialization, but in general this works nicely
> Unify `initializer_list<T>` constructors

- NEWS.md
- cpp11test/R/cpp11.R
- cpp11test/src/cpp11.cpp
- cpp11test/src/strings.cpp
- inst/include/cpp11/strings.hpp
I have determined that the `unwind_protect()`s being utilized in the string proxy assignment operator and the string `push_back()` operator are doing much more damage than they are worth.
- No other proxy assignment operator or `push_back()` operator for other vector types is performing this protection. Not even for lists, which has near identical implementations between `SET_VECTOR_ELT()` and `SET_STRING_ELT()`.
- Outside of `SET_STRING_ELT()` itself, the only thing to look at for "weirdness" would be the implicit conversion operator from `r_string` to `SEXP`. But that's a no-op, it just returns the underlying `data_`, so there is no need for `unwind_protect()` for that.
Because of the above 2 points, I've determined that removing the `unwind_protect()`s in the string impl would not make …
> Remove very expensive `unwind_protect()` in string proxy assignment and push back

- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
Closes https://github.com/r-lib/cpp11/issues/374
> Move the smarts of `fill_buf()` to `r_vector.hpp`

- cpp11test/src/test-r_vector.cpp
- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
Closes https://github.com/r-lib/cpp11/issues/369
> Take control over resizing to enforce required invariants

- NEWS.md
- cpp11test/src/test-doubles.cpp
- cpp11test/src/test-integers.cpp
- cpp11test/src/test-list.cpp
- inst/include/cpp11/r_vector.hpp
> Add missing read only implementation for `x.at("name")`

- NEWS.md
- cpp11test/src/test-matrix.cpp
- cpp11test/src/test-r_vector.cpp
- inst/include/cpp11/matrix.hpp
- inst/include/cpp11/r_vector.hpp
Reverts part of #383, specifically the note here https://github.com/r-lib/cpp11/pull/383/files#r1723749948
We really do need to call `Rf_shallow_duplicate()` because we want ALL of the attributes on the `rhs` to get copied over, even `dim` and `dimnames`.
`reserve_data()` is meant to be used when we KNOW we have a vector that `push_back()` has been called on, which should hopefully never be a `matrix` (there is no `matrix` API for this). If that holds, then it is ok that the `dim` and `dimnames` attributes get dropped on growth (i.e. during a `push_back()`) and truncation (i.e. in the `SEXP` operator).
The downside of this comes up when you do: `push_back()`, then use the copy constructor, then return that value. The copy constructor retains all the extra capacity (meaning the allocation …
> Shallow duplicate in `r_vector(const r_vector& rhs)` constructor after all

- cpp11test/src/test-r_vector.cpp
- inst/include/cpp11/r_vector.hpp
Found when looking at marquee failures
I don't think it makes sense to put this in `get_p()` itself. Many times we use `get_p()` but we know the data is not `R_NilValue` already.
> Guard uses of `get_p()` against `R_NilValue`

- NEWS.md
- cpp11test/src/test-environment.cpp
- inst/include/cpp11/R.hpp
- inst/include/cpp11/environment.hpp
- vignettes/FAQ.Rmd
> Remove usage of `Rf_findVarInFrame3()`

- NEWS.md
- cpp11test/src/test-r_vector.cpp
- inst/include/cpp11/r_vector.hpp
Closes https://github.com/r-lib/cpp11/issues/360
Closes https://github.com/r-lib/cpp11/issues/334
Expands on https://github.com/r-lib/cpp11/commit/686ae04f4c239735bdbe3e462731ae650ec6a225 to carry over some of these changes to `iterator` as well (i.e., not just `const_iterator`). Note that I have not changed `iterator` to be a `random_access_iterator_tag`, I left it as a `forward_iterator_tag`. Making a random access iterator requires many extra methods. I don't even think we implement all of them for `const_iterator`. I've added some comments about that and if we have issues in the future with iterators we should look and see if we just need more methods.
> Enable copy assignment operator for `iterator` class

- NEWS.md
- cpp11test/src/test-data_frame.cpp
- inst/include/cpp11/data_frame.hpp
The internal calc_nrow() doesn't (want to) implement the full vctrs logic, this offers a way for callers to construct a valid data frame in all corner cases.
> Allow passing number of rows from outside

- NEWS.md
- inst/include/cpp11/function.hpp
Closes #294 
In theory this is as simple as changing `SEXP` to `sexp` in `cpp11::function`.
In practice, doing _just_ that breaks some protection list related "count" tests. In the tests we assert that the size of the protection list starts at 0 at the beginning of the test, and we'd like to keep that nice assertion / property. However, if we just change to `sexp` then the count won't start at 0 if we've run the `message()` related tests first. That's because `message()` previously maintained a `static cpp11::function` variable holding `base::message`. Switching to `sexp` means that we now always maintains a protection list count of >0, because it never releases `base::message`. My solution is to switch away from `static cpp11::function` to a lower level method through `r_message()` that …
> Protect the function wrapped by `cpp11::function`

- inst/include/cpp11/doubles.hpp
- inst/include/cpp11/integers.hpp
- inst/include/cpp11/list.hpp
- inst/include/cpp11/logicals.hpp
- inst/include/cpp11/r_vector.hpp
- inst/include/cpp11/raws.hpp
- inst/include/cpp11/strings.hpp
Hi Davis
I hope you are doing well.
I am using cpp11 with vendoring to run my codes in the [Niagara](https://www.scinethpc.ca/niagara/) clusters. When I run my codes there, I get these warnings
```
── R CMD INSTALL ───────────────────────────────────────────────────────────────
─  installing *source* package ‘blazebenchmark’ ... (386ms)
** using staged installation
** libs
g++ -std=gnu++14 -I"/scinet/niagara/software/2019b/opt/gcc-8.3.0/r/4.2.2-batteries-included/lib64/R/include" -DNDEBUG   -I/usr/local/include   -DARMA_OPENMP_THREADS=40 -I../inst/include -fpic  -O2 -ftree-vectorize -march=native  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c 01_own_functions.cpp -o 
../inst/include/cpp11/r_vector.hpp:425:2: warning: extra ‘;’ [-Wpedantic] …
```
> fix compilation warnings on Niagara clusters

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
- cpp11test/src/safe.cpp
- cpp11test/src/test-as.cpp
- cpp11test/src/test-doubles.cpp
- cpp11test/src/test-integers.cpp
- cpp11test/src/test-protect-nested.cpp
- cpp11test/src/test-protect.cpp
- cpp11test/src/test-r_vector.cpp
- inst/include/cpp11/R.hpp
- inst/include/cpp11/altrep.hpp
- inst/include/cpp11/declarations.hpp
- inst/include/cpp11/environment.hpp
- inst/include/cpp11/protect.hpp
- Dropped support for R 3.6, as it is getting too challenging to try and continue to run CI for, and it is past our tidyverse EOL date by >6 months at this point.
- Removed as much dead code as possible. Anything that relied on `R_Version(3, 5, 0)`, `R_Version(3, 6, 0)`, or `>= R_Version(4, 0, 0)` has been removed because `R >= 4.0.0` is now required.
- Kept `altrep.hpp` and `HAS_ALTREP` because arrow uses it
- Kept `HAS_UNWIND_PROTECT` because arrow and systemfonts use it
> Drop support for R 3.6 and remove dead code

- NEWS.md
- inst/include/cpp11/R.hpp
Closes https://github.com/r-lib/cpp11/pull/404
Closes https://github.com/r-lib/cpp11/issues/403
> Conditionally define `R_NO_REMAP` and `STRICT_R_HEADERS`

- NEWS.md
- inst/include/cpp11/r_vector.hpp
> Attempt to fix rchk issue related to `names`

- NEWS.md
- inst/include/cpp11/altrep.hpp
- inst/include/cpp11/declarations.hpp
- inst/include/cpp11/protect.hpp
Follow up to #411 since textshaping used `CPP11_UNWIND`. Related to https://github.com/r-lib/cpp11/issues/414
> Restore `CPP11_UNWIND` for backwards compatibility

- NEWS.md
- inst/include/cpp11/R.hpp
- inst/include/cpp11/named_arg.hpp
- inst/include/fmt/format.h
> Remove whitespace in operator literal declarations (issue #447)

- .github/workflows/R-CMD-check.yaml
- .github/workflows/format.yaml
GitHub Actions is removing this old runner
> Forced move from Ubuntu 20 to 22
